### ISSUE TITLE
Type Theme

### ISSUE THREAD

**Issue by peduarte** [radix-ui/design-system#138]
As @sidoshi mentioned below, it would be nice to add type checking for props against its respective theme scale, for example?

```js
const theme = {
  colors: {
    primary: 'royalblue'
  }
};

// This should pass
<Box bg="primary"></Box>

// This should fail
<Box bg="blue"></Box>
```

**Comment by sidoshi** [comment]
@peduarte Is this issue about making it possible to type the value props based on theme? For example, if I have a theme with `primary` and `secondary` as only possible colors:

This should be invalid

```js
<Box color="blue"></Box>
```

and only values from theme should be allowed:

```js
<Box color="primary"></Box>
```

If not, should I create a new issue to track that?

For more context: https://github.com/chakra-ui/chakra-ui/issues/242

**Comment by peduarte** [comment]
@sidoshi Hey there 👋 

Yeah, that's exactly what this issue is about. Sorry about the lack of description, I added it just as a self reminder 😄 I'll add a better one now.

**Comment by sidoshi** [comment]
Let me know if I can help you in any way to implement this

**Comment by peduarte** [comment]
@sidoshi Thanks for the kind offer, if you want to have a go and create a PR I'd love to take a look. Thanks!

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
