### ISSUE TITLE
Should radix-system abstract all styled-system imports?

### ISSUE THREAD

**Issue by TheSisb** [radix-ui/design-system#142]
I like the ideas in radix-system and intend to use it for my own work, great job! 

I was wondering why you didn't fully abstract styled-system though, so we can just do:
`import {css, themeGet} from '@modulz/radix-system';` and not need to think about `styled-system/[theme-get|css|core]` at all?

Thanks for building this!

**Comment by peduarte** [comment]
Hey @TheSisb Yeah, I feel you - I had the same thought yesterday but was unsure whether that was a good idea. Now that you mentioned it, it makes me think that maybe it's a good thing to do after all.

I think I'm gonna consider this 👍 

But if I export `css` from `radix-system` I'd like it to be typed, so I'll probably have to create some Typings for it first.

Thanks!

**Comment by TheSisb** [comment]
Awesome! And typings would be great 🕺

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
