### ISSUE TITLE
shouldForwardProp - or export all propNames? 

### ISSUE THREAD

**Issue by Zn4rK** [radix-ui/design-system#163]
Right now I'm using styled-system, and it works great. I had a few minor issues with their typings, but I've managed to work around it. 

I would love to have something like [styled-system shouldForwardProp](https://github.com/styled-system/styled-system/blob/master/packages/should-forward-prop/) in this project. 
I'm only using the props-export in my projects, but maybe something similar could be done here?

**Comment by peduarte** [comment]
Yeah, I've been thinking about this for a while. I will definitely look into this at some point in the future, but if you have any ideas feel free to share. Will leave this open as a reminder 😉

**Comment by peduarte** [comment]
Now that Styled Components support this feature, we should be able to implement it https://github.com/styled-components/styled-components/pull/3006

**Comment by lucastobrazil** [comment]
Thinking out loud on this topic, it looks like projects needs the following:

1. Ability to call the `shouldForwardProp` function (just implemented in styled-components/styled-components#3006) ✅
2. The filtering function [@emotion/is-prop-valid](https://github.com/emotion-js/emotion/tree/master/packages/is-prop-valid) 
3. Ability to also pass in custom / extra props


I think for (2), we basically need to implement `is-prop-valid` for s-c too, or to even propose that emotion make it a more generic package. Looking under the hood that packages seems to just be copying from react's list of valid props and filtering them out. 

Thoughts here? I reckon creating a generic is-props-valid package would be cool and then using that in conjunction with `shouldForwardProp`

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
