### ISSUE TITLE
yarn init is yarn built in command

### ISSUE THREAD

**Issue by widyakumara** [radix-ui/design-system#231]
initialising radix after fresh clone is currently using `yarn init` which is [yarn built in command](https://classic.yarnpkg.com/en/docs/cli/init/).

**screenshot: `yarn init`**
![radix-yarn-init](https://user-images.githubusercontent.com/596434/77311749-4cf36280-6d33-11ea-9cf2-fdca6c1bdeb3.png)

**screenshot: `yarn init canceled`**
![radix-yarn-init-canceled](https://user-images.githubusercontent.com/596434/77311759-5086e980-6d33-11ea-80f5-80db13c8c189.png)

alternatively, use `yarn postinstall` to automatically run `yarn radix-system:build && yarn radix:build` after running `yarn` (or `yarn install`)

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
