### ISSUE TITLE
Treeshaking

### ISSUE THREAD

**Issue by raunofreiberg** [radix-ui/design-system#249]
Hey 👋

I'm not sure if this is an actual issue for now, but I noticed that design systems generated by Modulz (incl. Radix) are bundled into a single `index.es.js` file, which makes treeshaking un-used components practically impossible. Webpack and other bundlers are unable to safely remove possibly dead code when dealing with a bundled library.  See more: https://github.com/webpack/webpack/issues/9337

Something to consider is using Rollup's [`preserveModules`](https://rollupjs.org/guide/en/#preservemodules) which would preserve the directory structure, and not bundle the components into a single file, but rather have an `index.js` which would export all of the components from their respective files, which _should_ make detecting side effects easier, and thus treeshaking more effective.

I think it is reasonable to expect that design systems created via Modulz would allow consumers not to include all of the components in their final application. Especially since all design systems are published with all the primitives included (not sure if you can delete these?)

I just thought I'd throw the ball out there since I'm working on a similar problem for our design system, and hopefully get your take on this! 🙃

Thanks 👊

**Comment by StephenHaney** [comment]
Hey, this is terrific timing – we are internally debating the merits of one way versus another right now.

The next version on production will actually work exactly how you are suggesting... the export will look like this:

```
Button.js
Button.d.ts
index.js
index.d.ts
Switch.js
Switch.d.ts
// etc
```

and inside `index.js` it will just export each component from the respective file.

Seems better all around, right? The only downside I can think of is you can't throw the whole thing into a script tag and skip webpack, but that's not really relevant in our case.

Thanks for the feedback and please let us know if that matches what you're thinking.

CC @hadihallak @benoitgrelard

**Comment by raunofreiberg** [comment]
That's awesome!

Yeah. I had a similar approach in mind, where `package.json` would have:

```
"module": "lib/index.es.js"
```

and the `lib` itself would be 

```
lib/
├── components
    ├── Button
        ├── Button.js
        └── Button.d.ts
└── index.es.js 
```

I  think each component would need to also have a `package.json` with `"sideEffects": false` to make Webpack skip the whole module.

> The only downside I can think of is you can't throw the whole thing into a script tag and skip webpack, but that's not really relevant in our case.

If necessary, it is possible to include a UMD bundle in the library as well and make that available via `"main": "lib/index.js"` in the root `package.json`. This should make it possible to use it directly in the browser 🙃

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
