### ISSUE TITLE
Docs for Responsive Design

### ISSUE THREAD

**Issue by iwatakeshi** [radix-ui/design-system#257]
Hi! I haven't used the library yet, but I wanted to say that this looks awesome so far. I also wanted to add that it might be helpful to add some docs for responsive design. I had to look at the actual code in the docs repo to see how you guys made it responsive 😅 . I almost 😭 when I looked at the docs to see no examples of responsive design ([unless I missed it?](https://radix.modulz.app/docs/api/)).

Anyways, great job guys. Hopefully switching from `theme-ui`/`system-system`/`[insert framework x]`to `Radix` will lead to a better DX.

**Comment by peduarte** [comment]
Hey there, thanks for raising this.

That's a great idea, I'll make sure to add a dedicated section about responsive design. 

**Note:** I wouldn't personally recommend using Radix just yet. It's still in Alpha and it's heavily WIP, with breaking changes happening often.

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
