### ISSUE TITLE
Why onValueChange for <Select>?

### ISSUE THREAD

**Issue by crswll** [radix-ui/design-system#259]
All of the other components seem to work like their native counterparts. Is there a specific reason `<Select>` doesn't?

With some other components that I tried (Switch, Input, Textarea, Slider)  I can do things like `on(Focus|Blur|Change)` and it behaves as expected but Select doesn't use any of these.

**Comment by peduarte** [comment]
Yeah, it's because it's a custom select, so we wouldn't be able to return you the native `event`, so to remove that expectation we called it `onValueChange`, since the `value` is the only thing you receive

Does that make sense?

Would you still prefer it to be called `onChange` even if you don't get the native `event`?

**Comment by crswll** [comment]
Ah, it makes more sense when that part is explained a bit. I definitely wouldn't name it onChange without a legit event to work with. The lack of a focus and blur callbacks is interesting. Do you think it's worth having similar callbacks for focus and blur on it?

**Comment by peduarte** [comment]
I think it's worth debating. I don't see any downsides with having it.

Pinging @benoitgrelard

**Comment by benoitgrelard** [comment]
Yeah that's a tricky one, given that the Button is what actually gets focused/blurred… I'm not entirely sure what's the pattern or even what's expected in this case. @chancestrickland Did you get into this with Reach UI's listbox?

**Comment by benoitgrelard** [comment]
Might also potentially be linked to modulz/modulz#1092

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
