### ISSUE TITLE
[Select] Does not work with SSR

### ISSUE THREAD

**Issue by raunofreiberg** [radix-ui/design-system#280]
As per our conversation with @peduarte:

## Issue

Using `Select` in a Next.js server-rendered page throws this error related to mismatched id-s:

![image](https://user-images.githubusercontent.com/23662329/87872315-fdaaff00-c9bf-11ea-8886-afca360d9ce4.png)

## Steps to reproduce

1. Use `Select` on any server-rendered page. For example, I'm able to reproduce this error by using it on the ["Under the spotlight: Select" MDX article.](https://github.com/modulz/modulz-website/blob/master/pages/blog/under-the-spotlight-select/index.mdx)
2. The error will be gone in production, but the component does not work as intended

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
