### ISSUE TITLE
Issues with `Th` and `Td` styles

### ISSUE THREAD

**Issue by chaance** [radix-ui/design-system#285]
While building out a new docs page, I pulled in the Radix table components and noticed a few issues with the current implementation.

For reference, this is the table I'm working on:

![image](https://user-images.githubusercontent.com/3082153/99009309-b6132a80-24fc-11eb-9367-08d734e7f2ce.png)

The main issue is that the styling of `Th` assumes a scope of `"col"` (assumes that heading cells are at the top of the table). When used with a scope of `"row"`, a few things break. `Th` cells are underlined unlike `Td` cells. Also, because `Th` uses `:last-of-type` to remove padding from the last cell, the padding is removed when `scope` is set to `"row"` where the `Th` is likely the first cell rather than the last.

I can get around the first styling issue by using `<Td as="th" />`, but this doesn't solve the `last-of-type` problem. Further, I get a TS error saying that `Td` doesn't recognize the `as` prop even though it works fine. I think we probably should consider supporting `as` for table elements, even though I sort of understand why we probably decided not to at some point.

Here's a reproduction of the issue with my hacked solution in place. See `KeyboardInteractionTable.tsx`, line 20 that explains in context. https://codesandbox.io/s/young-tdd-ttm52?file=/src/KeyboardInteractionTable.tsx

## Potential solutions

* Add typing to support `as` prop.

* Change `:last-of-type` to `:last-child` to remove padding. I think this is probably ok since you shouldn't have arbitrary elements in a table row, but if there are edge cases I'm not considering, `:last-of-type:not([scope="row"])` could also work.

* Don't assume that a `th` is always inside of `thead` and remove the underline/bottom spacing styles from `Th`. I think we could probably replicate the look by adding those styles to `Thead` instead, which should always be at the top of a table.

* Add a context provider to `Thead` so that `Th` knows when it's in a header and when it's not, and adjust styles accordingly.

**Comment by peduarte** [comment]
Closing this since Radix is being deprecated. Moved to https://github.com/radix-ui/radix-legacy
