### ISSUE TITLE
Basic Slider Excample Broken

### ISSUE THREAD

**Issue by pdevito3** [radix-ui/design-system#288]
The [basic example](https://radix-ui.com/primitives/docs/components/slider#basic-example) for the slider is broken. Just getting started with the component, but it looks like the `Slider.Range` needs to be inside the `Slider.Track`?

**Comment by colmtuite** [comment]
Not sure what you mean? What's "broken" about it? It works fine.

**Comment by pdevito3** [comment]
hmm already wiped it for another approach. tried repoing in codesandbox for you, but couldn't remember what I did. Does look like the base example worked though exactly as is, so it must have been something i was doing. 

regardless, fwiw the docs are confusing where it says `The range part. Must live inside Slider.Track.` but the example isn't inside of it:
```js
  <Slider.Root>
    <Slider.Track>
      <Slider.Thumb />
    </Slider.Track>
    <Slider.Range />
  </Slider.Root>
```

**Comment by colmtuite** [comment]
In the example, the range is inside the track. I'm not sure what you mean.

<img width="410" alt="Screenshot 2020-12-24 at 05 57 49" src="https://user-images.githubusercontent.com/805073/103064875-03c78c00-45ad-11eb-9709-9315b33ac630.png">

**Comment by pdevito3** [comment]
sorry, i meant to link to the [anatomy tag](https://radix-ui.com/primitives/docs/components/slider#anatomy)

**Comment by colmtuite** [comment]
Ah, I see. Yep this looks like a bug. Thanks!

For future reference, the website repo is the best place to report documentation issues. Thanks.

**Comment by pdevito3** [comment]
yup, apologies. thought i was in there, but must have accidentally went back to design system.
