### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexanderl19** [radix-ui/design-system#370]
The repo doesn't currently have a license, however this issue was brought up previously in #171 and resolved in #172. As stated in the previous issue, if the intent is to still keep the project under the MIT license, it would be nice to have the explicit file. The file was removed in 0e8e622.

**Comment by benoitgrelard** [comment]
That was probably a mistake, let me find out.

**Comment by alexanderl19** [comment]
Thanks! Using Radix and Stitches has really been a joy!
